### ISSUE TITLE
Review does not update username for author

### ISSUE THREAD

**Issue by Thanawas-Sirilertsathit** [PanidaRumriankit/ku-vein#187]
* I added review into a course without using pen name. 
* I edited the profile username. 
* The review does not fetch my new username so it shows user_8 like it does not update.

So what I got is still user_8 not new username which may cause confusion for other users.

<img width="721" alt="image" src="https://github.com/user-attachments/assets/b5d4d72f-2414-4910-b86f-8a0680d1d28c">

**Comment by NoMoneyDev** [comment]
oh noh

**Comment by NoMoneyDev** [comment]
Solved in #211
