### ISSUE TITLE
Review sharing does not work

### ISSUE THREAD

**Issue by KhunakornP** [PanidaRumriankit/ku-vein#191]
## **Bug**
Review sharing does not work. Gives: /review/undefined on copy.

## **How To Reproduce**
1. Go to the main page
2. Click share
3. Click copy link

## **Expected behavior**
A link for sharing the review, Either with Facebook, X (Twitter) or a valid link to the review is given.

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

**Comment by PeanutPK** [comment]
Thanks for the issue I am working on that feature rn so it doesn't work ehe
