### ISSUE TITLE
Cannot edit review on main page

### ISSUE THREAD

**Issue by KhunakornP** [PanidaRumriankit/ku-vein#192]
## **Bug**
When clicking on the edit button nothing happens.

## **How To Reproduce**
1. Click the edit review button.

## **Expected behavior**
A page or modal appears and the user can edit the review.

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

**Comment by PeanutPK** [comment]
I am working on this one too xDDDDD
