### ISSUE TITLE
Bookmark page returns 404

### ISSUE THREAD

**Issue by KhunakornP** [PanidaRumriankit/ku-vein#193]
## **Bug**
When clicking the bookmark link, the site returns 404 page not found.

## **How To Reproduce**
1. Click profile icon
2. Click bookmark

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## **Screenshots**
![404bookmark](https://github.com/user-attachments/assets/7cf528ac-b52d-482f-8736-42d4cff34211)

**Comment by PanidaRumriankit** [comment]
Removed the page. Thanks for your time.
