### ISSUE TITLE
I can review the same subject twice?

### ISSUE THREAD

**Issue by Thanawas-Sirilertsathit** [PanidaRumriankit/ku-vein#198]
Is this a kind of illegal action?![image](https://github.com/user-attachments/assets/d9f63c9b-2c23-4530-b091-0c43b9dba679)

**Comment by Thanawas-Sirilertsathit** [comment]
It will affect the average of satisfaction score I guess.

**Comment by PeanutPK** [comment]
We will cap to three reviews per person per course 👍

**Comment by Ichi1234** [comment]
Done
