### ISSUE TITLE
Unexpected notifications appearing after login

### ISSUE THREAD

**Issue by PHIMNADA024** [PanidaRumriankit/ku-vein#200]
## The problem
Upon logging in, I noticed that I received four notifications all set to the same time. These notifications seem to be default notifications or system-generated ones, but it’s unclear why they appear immediately after login when I haven't taken any actions.

## How to reproduce the problem
1. Log in to the system.
2. Click on the notification icon (bell icon).
3. Observe that four notifications appear, all set at the same time as the login.

## Expected Behavior
Notifications should only appear based on user actions or relevant events, not as default or automatic notifications upon logging in.

## Screenshot
![image](https://github.com/user-attachments/assets/16744d39-66ba-43cb-9f22-3ae15c443edc)

**Comment by PanidaRumriankit** [comment]
It's a "will not be implemented anymore" feature. I forgot to delete it from the layout. Thank you for your time.
